# this file deploys in kubernetes the complete "exampleMicroservices" project (or at least how it is today)
# in Kubernetes. It contains the "meuServico" container that takes requests from another container, and 
# the "servidorweb" container that connects in the aforementioned container and also hosts a web page with
# results. This done using declarative Kubernetes. 
# Tested in Microk8s. Usage:
# microk8s.kubectl apply -f deployMeuservicoServidorweb.yml       # to deploy
# microk8s.kubectl get all                                        # to get the IP of the LoadBalancer service created
# curl <IP of the load balancer service created>:5000             # to see results. 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuservico
spec:
  selector: 
    matchLabels: 
      app: meuservico
  replicas: 1
  template:
    metadata:
      labels:
        app: meuservico
    spec:
      containers:
        - image: jrkessl/meuservico:latest
          name: vs
---
apiVersion: v1
kind: Service
metadata:
  name: meuservico-cip
spec:
  type: ClusterIP
  ports: 
    - port: 50051
  selector: 
    app: meuservico
---
apiVersion: v1
kind: Service
metadata:
  name: servidorweb-lb
spec:
  type: LoadBalancer
  ports: 
    - port: 5000
  selector: 
    app: servidorweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servidorweb
spec:
  selector:
    matchLabels:
      app: servidorweb
  replicas: 1
  template:
    metadata:
      labels:
        app: servidorweb
    spec:
      containers:
        - image: jrkessl/servidorweb:latest
          name: servidorweb
          env:
            - name: VAR_MEUSERVICO_HOST
              value: meuservico-cip
          ports:
            - containerPort: 5000
