apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: examplemicroservice
  # namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: path.example
    http:
      paths:
      - path: /path
        pathType: Prefix
        backend:
          service:
            name: servidorweb-np
            port:
              number: 5000
  - host: nginx.example
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: servidorweb-np
            port:
              number: 5000