# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meuservico.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'meuservico.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10meuservico.proto\"\x18\n\nRequisicao\x12\n\n\x02id\x18\x01 \x01(\x05\"\x19\n\x08Resposta\x12\r\n\x05texto\x18\x01 \x01(\t\"\'\n\tResposta2\x12\r\n\x05texto\x18\x01 \x01(\t\x12\x0b\n\x03num\x18\x02 \x01(\x05\x32x\n\nMeuservico\x12\"\n\x08\x63hamada1\x12\x0b.Requisicao\x1a\t.Resposta\x12#\n\x08\x63hamada2\x12\x0b.Requisicao\x1a\n.Resposta2\x12!\n\x07\x65hPrimo\x12\x0b.Requisicao\x1a\t.Respostab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meuservico_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUISICAO']._serialized_start=20
  _globals['_REQUISICAO']._serialized_end=44
  _globals['_RESPOSTA']._serialized_start=46
  _globals['_RESPOSTA']._serialized_end=71
  _globals['_RESPOSTA2']._serialized_start=73
  _globals['_RESPOSTA2']._serialized_end=112
  _globals['_MEUSERVICO']._serialized_start=114
  _globals['_MEUSERVICO']._serialized_end=234
# @@protoc_insertion_point(module_scope)
