# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meuservico.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='meuservico.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10meuservico.proto\"\x18\n\nRequisicao\x12\n\n\x02id\x18\x01 \x01(\x05\"\x19\n\x08Resposta\x12\r\n\x05texto\x18\x01 \x01(\t\"\'\n\tResposta2\x12\r\n\x05texto\x18\x01 \x01(\t\x12\x0b\n\x03num\x18\x02 \x01(\x05\x32x\n\nMeuservico\x12\"\n\x08\x63hamada1\x12\x0b.Requisicao\x1a\t.Resposta\x12#\n\x08\x63hamada2\x12\x0b.Requisicao\x1a\n.Resposta2\x12!\n\x07\x65hPrimo\x12\x0b.Requisicao\x1a\t.Respostab\x06proto3'
)




_REQUISICAO = _descriptor.Descriptor(
  name='Requisicao',
  full_name='Requisicao',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Requisicao.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=44,
)


_RESPOSTA = _descriptor.Descriptor(
  name='Resposta',
  full_name='Resposta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='texto', full_name='Resposta.texto', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=71,
)


_RESPOSTA2 = _descriptor.Descriptor(
  name='Resposta2',
  full_name='Resposta2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='texto', full_name='Resposta2.texto', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num', full_name='Resposta2.num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['Requisicao'] = _REQUISICAO
DESCRIPTOR.message_types_by_name['Resposta'] = _RESPOSTA
DESCRIPTOR.message_types_by_name['Resposta2'] = _RESPOSTA2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Requisicao = _reflection.GeneratedProtocolMessageType('Requisicao', (_message.Message,), {
  'DESCRIPTOR' : _REQUISICAO,
  '__module__' : 'meuservico_pb2'
  # @@protoc_insertion_point(class_scope:Requisicao)
  })
_sym_db.RegisterMessage(Requisicao)

Resposta = _reflection.GeneratedProtocolMessageType('Resposta', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTA,
  '__module__' : 'meuservico_pb2'
  # @@protoc_insertion_point(class_scope:Resposta)
  })
_sym_db.RegisterMessage(Resposta)

Resposta2 = _reflection.GeneratedProtocolMessageType('Resposta2', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTA2,
  '__module__' : 'meuservico_pb2'
  # @@protoc_insertion_point(class_scope:Resposta2)
  })
_sym_db.RegisterMessage(Resposta2)



_MEUSERVICO = _descriptor.ServiceDescriptor(
  name='Meuservico',
  full_name='Meuservico',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=114,
  serialized_end=234,
  methods=[
  _descriptor.MethodDescriptor(
    name='chamada1',
    full_name='Meuservico.chamada1',
    index=0,
    containing_service=None,
    input_type=_REQUISICAO,
    output_type=_RESPOSTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='chamada2',
    full_name='Meuservico.chamada2',
    index=1,
    containing_service=None,
    input_type=_REQUISICAO,
    output_type=_RESPOSTA2,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ehPrimo',
    full_name='Meuservico.ehPrimo',
    index=2,
    containing_service=None,
    input_type=_REQUISICAO,
    output_type=_RESPOSTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEUSERVICO)

DESCRIPTOR.services_by_name['Meuservico'] = _MEUSERVICO

# @@protoc_insertion_point(module_scope)
